# Generated by Django 5.0.2 on 2024-02-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_comment_communication_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='comments',
            field=models.ManyToManyField(related_name='communications', to='communication.comment', verbose_name='comments'),
        ),
    ]
