# Generated by Django 5.0.2 on 2024-02-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_communication_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='communication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communication.communication', verbose_name='communication'),
        ),
    ]
