# Generated by Django 5.0.2 on 2024-03-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_remove_communication_comments_comment_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='youtube_video',
            field=models.CharField(blank=True, help_text="from Youtube's video URL copy the part after 'https://www.youtube.com/watch?v='.", max_length=50, null=True, verbose_name='Youtube video'),
        ),
    ]
