# Generated by Django 5.0.2 on 2024-03-01 12:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_blog_youtube_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=100000, null=True, verbose_name='description'),
        ),
    ]
