# Generated by Django 5.0.2 on 2024-03-01 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_blog_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='communication.blog', verbose_name='blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'blog like',
                'verbose_name_plural': 'blog likes',
            },
        ),
        migrations.CreateModel(
            name='CommunicationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='communication.communication', verbose_name='communication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'communication like',
                'verbose_name_plural': 'communication likes',
            },
        ),
    ]
