# Generated by Django 5.0.2 on 2024-03-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', verbose_name='image'),
        ),
    ]
