# Generated by Django 5.0.2 on 2024-03-17 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10000, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/', verbose_name='image')),
                ('document', models.FileField(blank=True, null=True, upload_to='message_documents/', verbose_name='document')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
